#!/bin/bash

BASH_BRed='\[\033[01;31m\]'
BASH_BGreen='\[\033[01;32m\]'
BASH_BBlue='\[\033[01;34m\]'
BASH_Color_Off='\[\033[00m\]'

RED='\033[0;31m'
GREEN='\033[0;32m'
GREENB='\033[1;32m'
NC='\033[0m'

function goToLastUpdatedVersion() {
	DESTDIR=$1
	for VERSION in `ls ${DESTDIR} -t`
	do
		VERSIONDIR="${DESTDIR}/${VERSION}"
		if [ -d $VERSIONDIR ]; then
			cd $VERSIONDIR
			return 0
		fi
	done
}

function goto() {
	if [ ! $# -eq 1 ]; then
		echo "Please specify the component name"
		return 0;
	fi

	PROJECT=$1
	WORKDIR="${BUILDDIR}/work"
	CUTLEN=$(( ${#WORKDIR} + 2 ))
	CANDIDATES=`find ${WORKDIR} -maxdepth 2 | cut -c ${CUTLEN}- | grep "${PROJECT}"`

	COUNT=$(echo "$CANDIDATES" | wc -l)
	if [ ${COUNT} -eq 1 ]; then
		if [ ${#CANDIDATES} -gt 0 ]; then
			goToLastUpdatedVersion "${WORKDIR}/${CANDIDATES}"
		else
			echo -e "${RED}Cannot find...${NC}"
			return 1
		fi
	else
		x=1
		candi=0
		for DIR in $CANDIDATES
		do
			if [[ "$DIR" == */${PROJECT} ]]; then
				goToLastUpdatedVersion "${WORKDIR}/${DIR}"
				return 0
			fi
		done

		for DIR in $CANDIDATES
		do
			if [[ "$DIR" == */*${PROJECT} ]]; then
				echo -e "${GREENB}${x}${NC}: ${DIR}"
				candi=$x
			elif [[ "$DIR" == */${PROJECT}* ]]; then
				echo -e "${GREEN}${x}${NC}: ${DIR}"
				if [ ${candi} -eq 0 ]; then
					candi=$x
				fi
			else
				echo "${x}: ${DIR}"
			fi
			x=$(( $x + 1 ))
		done
		echo -en "Choose one >> "
		read -r SEL
		x=1
		if [ "$SEL" == "" ]; then
			SEL=${candi}
		fi
		for DIR in $CANDIDATES
		do
			if [ "$SEL" == "$x" ]; then
				goToLastUpdatedVersion "${WORKDIR}/${DIR}"
				return 0
			fi
			x=$(( $x + 1 ))
		done
		echo -e "${RED}Wrong choice...${NC}"
		return 1
	fi
}

function icp() {
	trap 'continue' SIGINT
	if [ $# -lt 2 ]; then
		echo "Usage {# icp component target (ipkType)} e.g. '# icp search auto:'"
		return 1;
	fi
	pushd . &> /dev/null
	PROJECT=$1
	TARGET=$2
	WHICHIPK=$3
	RET=0
	goto $PROJECT
	if [ $? -eq 0 ]; then
		cd deploy-ipks/*
		if [ $? -eq 0 ]; then
			if [ "$WHICHIPK" == "" ]; then
				IPK=`ls | sort | head -n 1`
			else
				IPK=`ls *${WHICHIPK}* 2> /dev/null | sort | head -n 1`
			fi
			if [ "$IPK" != "" ] && [ -f $IPK ]; then
				scp $IPK $TARGET
			fi
		fi
	fi
	popd &> /dev/null
	trap - SIGINT
	return ${RET}
}

function oe() {
	trap 'continue' SIGINT
	if [ ! $# -eq 2 ]; then
		echo "Usage {# oe command component} e.g. '# oe compile qtbase'"
		return 1;
	fi
	pushd . &> /dev/null
	COMMAND=$1
	PROJECT=$2
	RET=0
	goto $PROJECT
	if [ $? -eq 0 ]; then
		cd temp
		FILE="run.do_${COMMAND}"
		if [ -f $FILE ]; then
			./${FILE}
			RET=$?
		else
			echo "[ERROR] Can't find '${COMMAND}' command file. Please to bitbake job first."
		fi
	fi
	popd &> /dev/null
	trap - SIGINT
	return ${RET}
}

function bb() {
	trap 'continue' SIGINT
	pushd . &> /dev/null
	cd $WEBOS_BASE_DIR
	bitbake $@
	popd &> /dev/null
	trap - SIGINT
}

function btail() {
	trap 'continue' SIGINT
	if [ $# -eq 0 ]; then
		echo "Usage {# btail component (command: default = compile)}"
		echo "\te.g. '# btail qtbase configure'"
		return 1;
	fi
	pushd . &> /dev/null
	PROJECT=$1
	COMMAND=$2
	if [ "$COMMAND" == "" ]; then
		COMMAND="compile"
	fi
	RET=1
	goto $PROJECT
	if [ $? -eq 0 ]; then
		FILE="temp/log.do_${COMMAND}"
		if [ -f $FILE ]; then
			tail -f ./${FILE}
			RET=0
		else
			echo "[ERROR] Can't find '${COMMAND}' command file. Please to bitbake job first."
		fi
	fi
	popd &> /dev/null
	trap - SIGINT
	return ${RET}
}

function bedit() {
	if [ $# -eq 0 ]; then
		echo "Usage {# bedit component (all, without this choose last layer)}"
		echo "\te.g. '# bedit account all'"
		return 1;
	fi
	PROJECT=$1
	COMMAND=$2
	SEARCHALL=0
	if [ "$COMMAND" == "all" ]; then
		SEARCHALL=1
	fi
	RET=1
	LAYERS=`sed 's/ ?= /=/' $WEBOS_BASE_DIR/conf/bblayers.conf | grep "^META" | grep meta-lg-webos`
	CANDIDATES=()
	x=0
	for i in $LAYERS
	do
		DIR=${i/*=\"\$\{TOPDIR\}\//}
		DIR=${DIR/\"/}
		pushd ${WEBOS_BASE_DIR} &> /dev/null
		COUNT=`find $DIR -type f -name "*$PROJECT*.bb*" | wc -l`
		FILES=`find $DIR -type f -name "*$PROJECT*.bb*"`
		popd &> /dev/null
		if [ $COUNT -eq 0 ]; then
			continue;
		elif [ $COUNT -eq 1 ]; then
			x=$(( $x + 1 ))
			if [ $SEARCHALL -eq 0 ]; then
				FILE=$FILES
				break;
			else
				CANDIDATES+=($FILES)
			fi
		else
			x=$(( $x + $COUNT ))
			for j in $FILES
			do
				echo $j
				CANDIDATES+=($j)
			done
		fi
	done
	if [ "$FILE" != "" ]; then
		vi $WEBOS_BASE_DIR/$FILE
	elif [ $x -gt 0 ]; then
		y=1
		for j in ${CANDIDATES[@]}
		do
			echo "${y}: ${j}"
			y=$(( $y + 1 ))
		done
		echo -en "Choose one (default: 1) >> "
		read -r SEL
		if [ "$SEL" = "" ]; then
			SEL=1
		fi
		FILE=${CANDIDATES[$(( $SEL - 1 ))]}
		if [ "$FILE" != "" ]; then
			vi $WEBOS_BASE_DIR/$FILE
		fi
	else
		echo "No search result for '$PROJECT'"
	fi
	unset FILE
	unset FILES
	unset CANDIDATES
	popd &> /dev/null
	return ${RET}
}

function @add() {
	NAME=$1
	if [ "${NAME:0:1}" == "@" ]; then
		echo -e "${RED}Don't use '@' as first character.${NC}"
		return 1
	fi

	EXIST=`alias @${NAME} 2> /dev/null`
	if [ $? -eq 0 ]; then
		echo -e "${RED}Already exist...${NC}"
		return 1
	fi

	# replace to relational dir if it is a child dir
	CMD="alias @${NAME}='cd ${PWD/${WEBOS_BASE_DIR}/\$\{WEBOS_BASE_DIR\}}'"
	eval $CMD
	echo $CMD >> $GO_CONFIG_FILE
	return 0
}

function @del() {
	NAME=$1
	EXIST=`alias @${NAME} 2> /dev/null`
	if [ $? -ne 0 ]; then
		echo -e "${RED}Doesn't exist...${NC}"
		return 1
	fi

	eval "unalias @${NAME}"
	sed -i "/@${NAME}=/d" $GO_CONFIG_FILE
}

function @list() {
	cat ${GO_CONFIG_FILE} | \
		grep "alias" | \
		sed "s/='cd / /g" | \
		sed "s/'//g" | \
		sed "s/\${WEBOS_BASE_DIR}/\$/g" | \
		awk '{ printf("%-10s %s\n",$2,$3) }'
}

if [ "$WEBOS_BASE_DIR" == "" ]; then
	export WEBOS_BASE_DIR=$PWD
	source ~/.bashrc

	# check build environment first
	if [ -f ./oe-init-build-env ]; then
		source ./oe-init-build-env
	else
		echo -e "${RED}No 'oe-init-build-env' file. Please run ./mcf first${NC}"
		exit 1
	fi

	# load config
	export GO_CONFIG_FILE="${WEBOS_BASE_DIR}/.wns_config"
	if [ -f $GO_CONFIG_FILE ]; then
		source $GO_CONFIG_FILE
	else
		echo -en "Shell nickname [webOS]: " && read nick
		if [ "$nick" == "" ]; then
			export PROMPT_NICK="webOS"
		else
			export PROMPT_NICK="$nick"
		fi
		echo "export PROMPT_NICK=$PROMPT_NICK" > $GO_CONFIG_FILE
	fi

	# PS1
	export PS1="S-${BASH_BRed}${PROMPT_NICK} ${BASH_BBlue}\w${BASH_BGreen}\$(__git_ps1 \" [%s]\")${BASH_Color_Off} \$ "
	export PROMPT_DIRTRIM=2

	# set aliases
	alias @base="cd \${WEBOS_BASE_DIR}"

	# add bb/btail completion
	if [ ! -e `type -t _bitbake` ]; then
		complete -F _bitbake bb
		complete -F _bitbake btail
	fi
else
	echo -e "${GREEN}Already in WNS(webOS navigation shell)${NC}"
	exit 0
fi
